### ISSUE TITLE
 WemosNeopixelControl Upload problem 

### ISSUE THREAD

**Issue by plabonhasan** [thearduinoguy/WemosNeopixelControl#1]
hello dear
sorry to say, your busy time i disturb you. 
I have a Upload problem WemosNeopixelControl

first Arduino IDE 1.8.7 (Boards manager 2.5.2) upload click then 100% upload them serial  monitor IP address not show.

I haven't artnet code 100pixel, same thing code upload them seriel monitor IP address show.

How can I upload your code , 

dear i am not professional coder, i am a graphic design artists, i like neopixel, many project working in neopixel, this is my YouTube channel    https://www.youtube.com/channel/UCqPP5mXtF0tPrpiGStgANFg

Please dear u can help me i need more pixel animation

what is 
Wemos D1 to allow passthrough UDP data

**Comment by plabonhasan** [comment]
what is Wemos D1 to allow passthrough UDP data

**Comment by thearduinoguy** [comment]
This is an issue with you not putting your correct wifi details in and obtaining the IP of your device, not the code.
